### ISSUE TITLE
Ensure date arithmetic works in Spark

### ISSUE THREAD

**Issue by evansd** [opensafely-core/cohort-extractor-v2#195]
One thing I omitted to do in #180 was get date arithmetic working correctly. Specifically the [date_difference_in_years](https://github.com/opensafely-core/cohort-extractor-v2/blob/7e253d72e1892bd99f5bdb781d65b08db025ffd0/cohortextractor/query_engines/base_sql.py#L477-L497) function will almost certainly only work on MSSQL and will need a different implementation for Spark.

To test this we'd need to add a column to the [Databricks test cohort](https://github.com/opensafely-core/cohort-extractor-v2/blob/7e253d72e1892bd99f5bdb781d65b08db025ffd0/tests/backends/test_databricks.py#L82-L99) which uses the `age_as_of()` function; watch it fail; and then work out what further abstractions we need to add to the `BaseSQLQueryEngine` class to get this working in both MSSQL and Spark.

**Comment by bloodearnest** [comment]
We get a missing dateadd error

`Undefined function: 'dateadd'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.`

This is query that was generated:

```sql
SELECT tmp_20211110_228817210c25_group_table_0.patient_id        AS patient_id,
       tmp_20211110_228817210c25_group_table_1.date_of_birth     AS dob,
       CASE
         WHEN ( Dateadd(year, Datediff(year,
                tmp_20211110_228817210c25_group_table_2.date_of_birth, Cast(
                                                     '2020-01-01' AS DATE)),
                         tmp_20211110_228817210c25_group_table_2.date_of_birth)
                > Cast(
                       '2020-01-01' AS DATE) ) THEN
         Datediff(year, tmp_20211110_228817210c25_group_table_2.date_of_birth,
         Cast(
         '2020-01-01' AS DATE)) - 1
         ELSE Datediff(year,
tmp_20211110_228817210c25_group_table_2.date_of_birth,
              Cast(
                     '2020-01-01' AS DATE))
       END                                                       AS age,
       tmp_20211110_228817210c25_group_table_3.patient_id_exists AS
       prescribed_med,
       tmp_20211110_228817210c25_group_table_4.patient_id_exists AS admitted
FROM   tmp_20211110_228817210c25_group_table_0
       LEFT OUTER JOIN tmp_20211110_228817210c25_group_table_1
                    ON tmp_20211110_228817210c25_group_table_0.patient_id =
                       tmp_20211110_228817210c25_group_table_1.patient_id
       LEFT OUTER JOIN tmp_20211110_228817210c25_group_table_2
                    ON tmp_20211110_228817210c25_group_table_0.patient_id =
                       tmp_20211110_228817210c25_group_table_2.patient_id
       LEFT OUTER JOIN tmp_20211110_228817210c25_group_table_3
                    ON tmp_20211110_228817210c25_group_table_0.patient_id =
                       tmp_20211110_228817210c25_group_table_3.patient_id
       LEFT OUTER JOIN tmp_20211110_228817210c25_group_table_4
                    ON tmp_20211110_228817210c25_group_table_0.patient_id =
                       tmp_20211110_228817210c25_group_table_4.patient_id
WHERE  tmp_20211110_228817210c25_group_table_0.patient_id_exists = true 
```

**Comment by bloodearnest** [comment]
Lol, looks like it might just need an underscore: https://spark.apache.org/docs/latest/api/sql/index.html#date_add

**Comment by bloodearnest** [comment]
Aaaand datediff has a different signature, only does days difference:

https://spark.apache.org/docs/latest/api/sql/index.html#datediff

We'll need to specialise the `BaseSQLBackend.date_difference_by_year` function.

We could either do:

a) coarse specialisation and have mssql use it's special datediff(year, a, b) thing, and do the day/year arithmetic in the spark version

or b) specialised versions just return days difference, and we do the year calculations in SQL the same for all backends.

I'm leaning towards b) for consistency between backends, but would welcome comments from clueful folks @evansd @inglesp 
Option 1: specialise the DateDifferenceByYear construct via backend.

**Comment by evansd** [comment]
I don't think the "days to years" SQL will be that straightforward to do correctly, unless there's a clever trick I'm missing. It's use case is calculating people's age on a given date given their date of birth so it needs to correctly account for leap years.

**Comment by bloodearnest** [comment]
I was assuming that if spark's datediff function would account for leap years and give you an actual number of days between too dates.

I will test this assumption. Basically, I will check that mssql's `datediff(day, a, b)` == sparks `datediff(a, b)`, and we can see

**Comment by evansd** [comment]
I don't see how that helps us. I assume it does calculate the actual number of days correctly, but we need to convert that into years, don't we?

**Comment by bloodearnest** [comment]
Hmm, so I guess if we need age to be legally accurate, as opposed to biologically, then I guess so.

But, spark has no function to this as far as I can tell. So, to support it, we would have to do it ourselves anyway?

**Comment by bloodearnest** [comment]
https://spark.apache.org/docs/latest/api/sql/index.html#months_between seems completely inaccurate

**Comment by evansd** [comment]
> But, spark has no function to this as far as I can tell. So, to support it, we would have to do it ourselves anyway?

:( I think you're right. We've been relying on MSSQL's `date_add(year, ...)` to do this for us.

The other approach would be to decompose the date into year, month day parts and do the comparison logic ourselves which I think is just:
```py
diff = a_year_part - b_year_part
if b_month_part > a_month_part:
    diff -= 1
if b_month_part == a_month_part and b_day_part > a_day_part:
    diff -= 1 
```
That's obviously expressible in SQL but I don't know how elegantly it can be done.

**Comment by bloodearnest** [comment]
That seems reasonable and more portable (assuming you are ignoring days was we don't have the day part of dob).

I'll try that, hopefully it can be expressed in something generic and we don't need specialise at all

**Comment by bloodearnest** [comment]
Could we see a non-age use case for DateDifferenceInYears? It's only used in `age_as_of()` currently, but if it could potentially be used in a date with a day component (e.g. a clinical event)?

I don't think so, but though I'd check

**Comment by evansd** [comment]
I wouldn't want to rule it out. I also wouldn't want to rule out running in backends where we _do_ have exact date of birth.

I think we need to make this work in the general case and not just the with the specific dataset/use case we have at the moment.

**Comment by bloodearnest** [comment]
So, we don't currently rely on datediff for accutate year calculations anyway:

https://github.com/opensafely-core/cohort-extractor-v2/blob/main/cohortextractor/query_engines/base_sql.py#L488

We do some further date maths to determine the actual date arithmetic.

So, since `datediff(year, d1, d2)` seems to just do `year(d2) - year(date1)` (as the comment in the above and my tests suggest),
maybe we can just replace with `year(d2) - year(d1)`,  as `year` is supported in spark and sql?

https://spark.apache.org/docs/latest/api/sql/index.html#year

https://www.sqlservertutorial.net/sql-server-date-functions/sql-server-year-function/

Then we just need to specialise `dateadd` vs `date_add`

**Comment by evansd** [comment]
Right, yes it isn't `datediff` that we rely on to do anything clever for us, it's `dateadd`. So replacing `DATEDIFF(year, d1, d2)` with `year(d2) - year(d1)` as you suggest seems like a good move, but it doesn't really solve the problem which is that Spark's `date_add` has no units argument.

**Comment by bloodearnest** [comment]
Yep, I just realised that.
