### ISSUE TITLE
Just enough of a TPP backend to support a real study

### ISSUE THREAD

**Issue by benbc** [opensafely-core/cohort-extractor-v2#41]

**Comment by rebkwok** [comment]
Remaining TPP backend needed for the real Long Covid study:
- [ ] `pseudo_id` on `practice_registrations` table
- [ ] `nuts1_region_name` on  `practice_registrations` table
- [ ] `patient_address` table with `date_start`, `date_end`, `index_of_multiple_deprivation`, `msoa`, `patientaddress_id` columns (see #96)

**Comment by rebkwok** [comment]
I think this is all done now.  The only bit left are the things for `age_as_of`, which are needed for the simplified study too
