### ISSUE TITLE
Categorizing for bucketed values

### ISSUE THREAD

**Issue by benbc** [opensafely-core/cohort-extractor-v2#51]
- [x] simple single comparisons (`x > y`)
- [x] and/or conditions (`(x > y)` & `(y == z)`)
- [x] nesting conditions (`((x > y)` & `(y == z)) | (z == a)`)
- [ ] inverting conditions (`~((x > y)` & `(y == z))`)
- [ ] True/False comparisons

**Comment by rebkwok** [comment]
I realised that this one was essentially the same as #48, since all categorising is bucketing values.  The simple case is categorising with just `x > y`, the more complex case is and/or'ing conditions

**Comment by rebkwok** [comment]
Just noting for later that the current operator overloading doesn't work for the "between" shorthand (50 < x < 100), because that does an implicit `and` which we can't overload. The explicit version - `x > 50 & x < 100` - works fine.
