### ISSUE TITLE
Add support for multi-value code column in TPP hospitalizations table

### ISSUE THREAD

**Issue by benbc** [opensafely-core/cohort-extractor-v2#85]

**Comment by benbc** [comment]
@evansd Please can you confirm the semantics here? Here's my current understanding.

A single hospitalization event can have multiple codes associated with it, presumably because the patient had multiple notable features and/or things wrong with them when admitted and/or events during their stay. This is represented as a comma-separated list in the `Der_Diagnosis_All` column of the `APCS` table.

(I see that the old CE also allows similar querying of `APCS_Der.Spell_Primary_diagnosis`. Presumably we can leave that for later.)

When the researcher queries for hospitalizations with a given code, they want all events where _any_ of the codes recorded is _exactly equal_ to _any_ of the codes in the filter.

**Comment by evansd** [comment]
> When the researcher queries for hospitalizations with a given code, they want all events where any of the codes recorded is exactly equal to any of the codes in the filter.

This is correct, yes.

There's some further complications surrounding matching on prefixes and `X` suffixes being added which we can go into separately. But in a sense that's legacy complexity and what you've described are the semantics we should be aiming for.
